trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
- group: 'terraform-variables'
  

stages:
- stage: 'TfValidatePlan'
  displayName: 'Terraform Validate and Plan'
  jobs:
  - job: 'TerraformValidatePlan'
    displayName: 'Terraform Validate and Plan'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - checkout: self

    - task: TerraformTaskV1@0
      displayName: 'Terraform Init'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        backendServiceArm: '$(service-connection)'
        backendAzureRmResourceGroupName: '$(resource_group_name)'
        backendAzureRmStorageAccountName: '$(storage_account_name)'
        backendKey: '$(backendkey)'

    - task: TerraformTaskV1@0
      displayName: 'Terraform Validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        environmentServiceNameAzureRM: '$(service-connection)'

    - task: TerraformTaskV1@0
      displayName: 'Terraform Plan'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        environmentServiceNameAzureRM: '$(service-connection)'
        commandOptions: '-var-file=dev.tfvars'

- stage: 'TfDeploy'
  displayName: 'Terraform Deploy'
  dependsOn: 'TfValidatePlan'
  condition: succeeded('TfValidatePlan')
  jobs:
  - job: 'TerraformDeploy'
    displayName: 'Terraform Deploy'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - checkout: self

    - task: TerraformTaskV1@0
      displayName: 'Terraform Init'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        backendServiceArm: '$(service-connection)'
        backendAzureRmResourceGroupName: '$(resource_group_name)'
        backendAzureRmStorageAccountName: '$(storage_account_name)'
        backendKey: '$(backendkey)'

    - task: TerraformTaskV1@0
      displayName: 'Terraform Apply'
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        environmentServiceNameAzureRM: '$(service-connection)'
        commandOptions: '-auto-approve -var-file=dev.tfvars'