trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'terraform-variables'

stages:
- stage: 'Dev'
  jobs:
  - job: 'TerraformApplyDev'
    displayName: 'Terraform Init-Plan-Apply - Azure Resources - Dev'
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(service-connection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(System.DefaultWorkingDirectory)/.tf/app_service
          terraform init
          terraform plan -var-file=C:\Projects\CloudDevOpsForJavaReact\IaC-Terraform\dev.tfvars
          terraform apply -var-file=C:\Projects\CloudDevOpsForJavaReact\IaC-Terraform\dev.tfvars -auto-approve

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/.tf/app_service/*.tfstate'
        artifact: 'tfstateFiles'
        publishLocation: 'pipeline'

    - task: AzureFileCopy@4
      inputs:
        SourcePath: '$(System.DefaultWorkingDirectory)/.tf/app_service/*.tfstate'
        azureSubscription: '$(Service-Connection)'
        Destination: 'AzureBlob'
        storage: '$(storage_account_name)'  # Use the storage account name from Terraform
        ContainerName: '$(container_name)'  # Use the container name from Terraform
        BlobPrefix: 'tfstateFiles/'
