trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'terraform-variables'

stages:
- stage: 'Dev'
  jobs:
  - job: 'TerraformApplyDev'
    displayName: 'Terraform Apply - Dev'
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(service-connection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(System.DefaultWorkingDirectory)/.tf/app_service
          terraform init
          terraform plan -var-file=dev.tfvars
          terraform apply -var-file=dev.tfvars -auto-approve
      displayName: 'Terraform Apply - App Service - Dev'

# Add similar jobs for Acc and Prd stages with appropriate variable files and resource configurations
