trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
- group: 'terraform-variables'

stages:
- stage: 'Dev'
  jobs:
  - job: 'TerraformApplyDev'
    displayName: 'Terraform Init-Plan-Apply - Azure Resources - Dev'
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.7.4'
    
    # Initialize Terraform backend with reconfigure
    - powershell: |
       terraform init -reconfigure
      displayName: 'Terraform Init - Reconfigure Backend'
      workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
    
    - task: AzureCLI@2
      displayName: 'Run Terraform commands'
      inputs:
        azureSubscription: $(service-connection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd $(System.DefaultWorkingDirectory)/IaC-Terraform
          ls -la  # Optional: List files in the directory for troubleshooting
          terraform plan -var-file=dev.tfvars
          terraform apply -var-file=dev.tfvars -auto-approve
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'

    - powershell: |
       Set-Location -Path $(System.DefaultWorkingDirectory)/IaC-Terraform/.tf/app_service
       Get-ChildItem -Filter *.tfstate | Format-Table -AutoSize
      displayName: 'List .tfstate files'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/IaC-Terraform/.tf/app_service/*.tfstate'
        artifact: 'tfstateFiles'
        publishLocation: 'pipeline'

    - task: AzureFileCopy@4
      inputs:
        SourcePath: '$(System.DefaultWorkingDirectory)/IaC-Terraform/.tf/app_service/*.tfstate'
        azureSubscription: '$(Service-Connection)'
        Destination: 'AzureBlob'
        storage: '$(storage_account_name)'  
        ContainerName: '$(container_name)'  
        BlobPrefix: 'tfstateFiles/'
