trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Initialize Terraform'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
    command: 'init'
    backendServiceArm: 'skd-Cloud-Service-Connection'
    backendAzureRmResourceGroupName: $(Your-Resource-Group)
    backendAzureRmStorageAccountName: $(Your-Storage-Account)
    backendAzureRmContainerName: $(Your-Container)
    backendAzureRmKey: 'terraform.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Validate Terraform Configuration'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
    command: 'validate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Generate Terraform Plan'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
    command: 'plan'
    environmentServiceNameAzureRM: 'skd-Cloud-Service-Connection'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Apply Terraform Plan'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
    command: 'apply'
    environmentServiceNameAzureRM: 'skd-Cloud-Service-Connection'
    commandOptions: '-auto-approve'
