variables:
  resource_group_name: $[ variables['resource_group_name'] ]
  location: $[ variables['location'] ]
  
  storage_account_name_dev: $[ variables['storage_account_name_dev'] ]
  storage_account_name_acc: $[ variables['storage_account_name_acc'] ]
  storage_account_name: $[ variables['storage_account_name'] ]
  
  container_name_dev: $[ variables['container_name'] ]
  container_name_acc: $[ variables['container_name'] ]
  container_name: $[ variables['container_name'] ]
  
  admin_username: $[ variables['admin_username'] ]
  admin_password: $[ variables['admin_password'] ]

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  displayName: 'Deploy to Dev Environment'
  jobs:
  - job: Dev_Deployment
    displayName: 'Deploy to Dev'
    steps:
    - script: |
        echo "Deploying to Dev Environment"
        terraform init
        terraform plan -var="resource_group_name=${{ variables['resource_group_name'] }}" -var="location=${{ variables['location'] }}" -var="admin_username=${{ variables['admin_username'] }}" -var="admin_password=${{ variables['admin_password'] }}" -var="environment=dev"
        terraform apply -auto-approve -var="resource_group_name=${{ variables['resource_group_name'] }}" -var="location=${{ variables['location'] }}" -var="admin_username=${{ variables['admin_username'] }}" -var="admin_password=${{ variables['admin_password'] }}" -var="environment=dev"

- stage: Acc
  displayName: 'Deploy to Acc Environment'
  jobs:
  - job: Acc_Deployment
    displayName: 'Deploy to Acc'
    steps:
    - script: |
        echo "Deploying to Acc Environment"
        terraform init
        terraform plan -var="resource_group_name=$(resource_group_name)" -var="location=$(location)" -var="admin_username=$(admin_username)" -var="admin_password=$(admin_password)" -var="environment=acc"
        terraform apply -auto-approve -var="resource_group_name=$(resource_group_name)" -var="location=$(location)" -var="admin_username=$(admin_username)" -var="admin_password=$(admin_password)" -var="environment=acc"

- stage: Prd
  displayName: 'Deploy to Prd Environment'
  jobs:
  - job: Prd_Deployment
    displayName: 'Deploy to Prd'
    steps:
    - script: |
        echo "Deploying to Prd Environment"
        terraform init
        terraform plan -var="resource_group_name=$(resource_group_name)" -var="location=$(location)" -var="admin_username=$(admin_username)" -var="admin_password=$(admin_password)" -var="environment=prd"
        terraform apply -auto-approve -var="resource_group_name=$(resource_group_name)" -var="location=$(location)" -var="admin_username=$(admin_username)" -var="admin_password=$(admin_password)" -var="environment=prd"