trigger:
- none

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Dev
  displayName: 'Deploy to Dev Environment'
  jobs:
  - job: Dev_Deployment
    displayName: 'Deploy to Dev'
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Initialize Terraform'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        command: 'init'
        backendServiceArm: 'skd-Cloud-Service-Connection'
        commandOptions: '-var="environment=dev"'
        backendAzureRmStorageAccountName: 'skdstorageaccount'
        backendAzureRmContainerName: 'skdscontainerdev'
        backendAzureRmKey: 'terraform-dev.tfstate'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform Plan for Dev Environment'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        command: 'plan'
        

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Apply Terraform Configuration for Dev Environment'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC-Terraform'
        command: 'apply'
        
