trigger:
- main

pool:
  name: 'BRUNAL_LTP_4_SD'

variables:
  dockerRegistryServiceConnection: 'ARM-Service-Connection'
  dockerfilePath: 'react-and-spring-data-rest\dockerfile'
  imageName: 'react-and-spring-data-rest'
  containerRegistry: 'skdcontainerregistry.azurecr.io'
  dockerImageTag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and push an image to container registry'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(containerRegistry)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(dockerImageTag)
