trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub-Service-Connection'
  dockerfilePath: 'react-and-spring-data-rest/dockerfile'
  imageName: 'react-and-spring-data-rest'
  dockerImageTag: '$(Build.BuildId)'

steps:
- task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
      jdkDestinationDirectory: "/builds/binaries/externals"
      cleanDestinationDirectory: true

- script: |
    mvn clean package
  displayName: 'Build the application'

- task: Docker@2
  displayName: 'Build and push an image to container registry'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'your-dockerhub-username/$(imageName)'  # Replace 'your-dockerhub-username' with your Docker Hub username
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(dockerImageTag)
