trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub-Service-Connection'
  azureSubscription: 'ARM-Service-Connection'
  dockerfilePath: 'react-and-spring-data-rest/dockerfile'
  imageName: 'react-and-spring-data-rest'
  dockerImageTag: '$(Build.BuildId)'
  appName: 'skdappservice'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: "11"
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
    
- script: |
    cd $(System.DefaultWorkingDirectory)/react-and-spring-data-rest
    mvn clean package
  displayName: 'Build the application'

- task: Docker@2
  displayName: 'Build and push an image to container registry'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'devopsskd/$(imageName)'  
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(dockerImageTag)

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    containers: 'devopsskd/$(imageName):$(dockerImageTag)'