trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub-Service-Connection'
  dockerfilePath: 'react-and-spring-data-rest/dockerfile'
  imageName: 'react-and-spring-data-rest'
  dockerImageTag: '$(Build.BuildId)'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: "11"
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
    
- script: |
    cd $(System.DefaultWorkingDirectory)/react-and-spring-data-rest
    mvn clean package
  displayName: 'Build the application'

- task: Docker@2
  displayName: 'Build and push an image to container registry'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'devopsskd/$(imageName)'  
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(dockerImageTag)
