# Use OpenJDK 11 as base image for building
FROM openjdk:11


# Copy the entire project to the container
COPY target/*.jar app.jar


# Expose port 8080 (if needed)
EXPOSE 8080

# Set the command to run when the container starts
CMD ["java", "-jar", "app.jar"]

#  instructing Docker to run a Java application 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]