# Use a base image with Maven to build the application
FROM maven:3.6.3-openjdk-11 AS build
WORKDIR /app

# Copy the source code to the container
COPY . .

# Build the application
RUN mvn clean package

# Create a new image with only the built JAR file
FROM openjdk:11-jre-slim
WORKDIR /app

# Copy the built JAR file from the build image
COPY --from=build /app/target/react-and-spring-data-rest-*.jar app.jar

# Expose the port used by the application
EXPOSE 8080

# Start the application when the container starts
CMD ["java", "-jar", "app.jar"]
